$(function(){

	var HanGuanJiHeIndex = 2;
	$("#addHanGuanJiHe").click(function(){
		var tempDelFileInfoId = "HanGuanJiHeIndex" + ++HanGuanJiHeIndex;
	    $str='';
        $str+='<tr>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="hanGuanJiHe_l1" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="hanGuanJiHe_l2" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="hanGuanJiHe_l3" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="hanGuanJiHe_l4" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="hanGuanJiHe_l5" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="hanGuanJiHe_l6" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="hanGuanJiHe_l7" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="hanGuanJiHe_l8" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="hanGuanJiHe_l9" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="hanGuanJiHe_l10" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="hanGuanJiHe_l11" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="hanGuanJiHe_l12" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="hanGuanJiHe_l13" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="hanGuanJiHe_l14" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="hanGuanJiHe_l15" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="hanGuanJiHe_l16" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="hanGuanJiHe_l17" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="hanGuanJiHe_l18" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="hanGuanJiHe_l19" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="hanGuanJiHe_l20" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="hanGuanJiHe_l21" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="hanGuanJiHe_l22" /></td>';
		$str+='<td align="center"><a id="'+tempDelFileInfoId+'" 	href="javascript:delTr(\''+tempDelFileInfoId+'\')" >删除</a></td>';
	    $str+='</tr>';
	    $("#hanGuanJiHe").before($str);

	});
	var WuFengGangGuanIndex = 2;
	$("#addWuFengGangGuan").click(function(){
		var tempDelFileInfoId = "WuFengGangGuanIndex" + ++WuFengGangGuanIndex;
	    $str='';
        $str+='<tr>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="wuFengGangGuan_l1" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="wuFengGangGuan_l2" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="wuFengGangGuan_l3" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="wuFengGangGuan_l4" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="wuFengGangGuan_l5" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="wuFengGangGuan_l6" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="wuFengGangGuan_l7" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="wuFengGangGuan_l8" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="wuFengGangGuan_l9" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="wuFengGangGuan_l10" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="wuFengGangGuan_l11" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="wuFengGangGuan_l12" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="wuFengGangGuan_l13" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="wuFengGangGuan_l14" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="wuFengGangGuan_l15" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="wuFengGangGuan_l16" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="wuFengGangGuan_l17" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="wuFengGangGuan_l18" /></td>';
		$str+='<td align="center"><a id="'+tempDelFileInfoId+'" 	href="javascript:delTr(\''+tempDelFileInfoId+'\')" >删除</a></td>';
	    $str+='</tr>';
	    $("#wuFengGangGuan").before($str);

	});
	var YouTaoGuanIndex = 2;
	$("#addYouTaoGuan").click(function(){
		var tempDelFileInfoId = "YouTaoGuanIndex" + ++YouTaoGuanIndex;
	    $str='';
        $str+='<tr>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="youTaoGuan_l1" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="youTaoGuan_l2" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="youTaoGuan_l3" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="youTaoGuan_l4" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="youTaoGuan_l5" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="youTaoGuan_l6" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="youTaoGuan_l7" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="youTaoGuan_l8" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="youTaoGuan_l9" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="youTaoGuan_l10" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="youTaoGuan_l11" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="youTaoGuan_l12" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="youTaoGuan_l13" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="youTaoGuan_l14" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="youTaoGuan_l15" /></td>';
		$str+='<td align="center"><a id="'+tempDelFileInfoId+'" 	href="javascript:delTr(\''+tempDelFileInfoId+'\')" >删除</a></td>';
	    $str+='</tr>';
	    $("#youTaoGuan").before($str);
	});
	var WanGuanJiHeIndex = 2;
	$("#addWanGuanJiHe").click(function(){
		var tempDelFileInfoId = "WanGuanJiHeIndex" + ++WanGuanJiHeIndex;
	    $str='';
        $str+='<tr>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="wanGuanJiHe_l1" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="wanGuanJiHe_l2" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="wanGuanJiHe_l3" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="wanGuanJiHe_l4" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="wanGuanJiHe_l5" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="wanGuanJiHe_l6" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="wanGuanJiHe_l7" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="wanGuanJiHe_l8" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="wanGuanJiHe_l9" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="wanGuanJiHe_l10" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="wanGuanJiHe_l11" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="wanGuanJiHe_l12" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="wanGuanJiHe_l13" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="wanGuanJiHe_l14" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="wanGuanJiHe_l15" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="wanGuanJiHe_l16" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="wanGuanJiHe_l17" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="wanGuanJiHe_l18" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="wanGuanJiHe_l19" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="wanGuanJiHe_l20" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="wanGuanJiHe_l21" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="wanGuanJiHe_l22" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="wanGuanJiHe_l23" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="wanGuanJiHe_l24" /></td>';
		$str+='<td align="center"><a id="'+tempDelFileInfoId+'" 	href="javascript:delTr(\''+tempDelFileInfoId+'\')" >删除</a></td>';
	    $str+='</tr>';
	    $("#wanGuanJiHe").before($str);

	});
	var JiuShiTouIndex = 2;
	$("#addJiuShiTou").click(function(){
		var tempDelFileInfoId = "JiuShiTouIndex" + ++JiuShiTouIndex;
	    $str='';
        $str+='<tr>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="jiuShiTou_l1" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="jiuShiTou_l2" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="jiuShiTou_l3" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="jiuShiTou_l4" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="jiuShiTou_l5" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="jiuShiTou_l6" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="jiuShiTou_l7" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="jiuShiTou_l8" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="jiuShiTou_l9" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="jiuShiTou_l10" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="jiuShiTou_l11" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="jiuShiTou_l12" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="jiuShiTou_l13" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="jiuShiTou_l14" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="jiuShiTou_l15" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="jiuShiTou_l16" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="jiuShiTou_l17" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="jiuShiTou_l18" /></td>';
		$str+='<td align="center"><a id="'+tempDelFileInfoId+'" 	href="javascript:delTr(\''+tempDelFileInfoId+'\')" >删除</a></td>';
	    $str+='</tr>';
	    $("#jiuShiTou").before($str);

	});
	var SiShiWuTouIndex = 2;
	$("#addSiShiWuTou").click(function(){
		var tempDelFileInfoId = "SiShiWuTouIndex" + ++SiShiWuTouIndex;
	    $str='';
        $str+='<tr>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="siShiWuTou_l1" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="siShiWuTou_l2" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="siShiWuTou_l3" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="siShiWuTou_l4" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="siShiWuTou_l5" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="siShiWuTou_l6" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="siShiWuTou_l7" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="siShiWuTou_l8" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="siShiWuTou_l9" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="siShiWuTou_l10" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="siShiWuTou_l11" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="siShiWuTou_l12" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="siShiWuTou_l13" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="siShiWuTou_l14" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="siShiWuTou_l15" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="siShiWuTou_l16" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="siShiWuTou_l17" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="siShiWuTou_l18" /></td>';
		$str+='<td align="center"><a id="'+tempDelFileInfoId+'" 	href="javascript:delTr(\''+tempDelFileInfoId+'\')" >删除</a></td>';
	    $str+='</tr>';
	    $("#siShiWuTou").before($str);

	});
	var DengJingSanTongIndex = 2;
	$("#addDengJingSanTong").click(function(){
		var tempDelFileInfoId = "DengJingSanTongIndex" + ++DengJingSanTongIndex;
	    $str='';
        $str+='<tr>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="dengJingSanTong_l1" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="dengJingSanTong_l2" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="dengJingSanTong_l3" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="dengJingSanTong_l4" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="dengJingSanTong_l5" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="dengJingSanTong_l6" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="dengJingSanTong_l7" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="dengJingSanTong_l8" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="dengJingSanTong_l9" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="dengJingSanTong_l10" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="dengJingSanTong_l11" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="dengJingSanTong_l12" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="dengJingSanTong_l13" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="dengJingSanTong_l14" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="dengJingSanTong_l15" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="dengJingSanTong_l16" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="dengJingSanTong_l17" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="dengJingSanTong_l18" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="dengJingSanTong_l19" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="dengJingSanTong_l20" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="dengJingSanTong_l21" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="dengJingSanTong_l22" /></td>';
		$str+='<td align="center"><a id="'+tempDelFileInfoId+'" 	href="javascript:delTr(\''+tempDelFileInfoId+'\')" >删除</a></td>';
	    $str+='</tr>';
	    $("#dengJingSanTong").before($str);

	});
	var YiJingSanTongIndex = 2;
	$("#addYiJingSanTong").click(function(){
		var tempDelFileInfoId = "YiJingSanTongIndex" + ++YiJingSanTongIndex;
	    $str='';
        $str+='<tr>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="yiJingSanTong_l1" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="yiJingSanTong_l2" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="yiJingSanTong_l3" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="yiJingSanTong_l4" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="yiJingSanTong_l5" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="yiJingSanTong_l6" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="yiJingSanTong_l7" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="yiJingSanTong_l8" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="yiJingSanTong_l9" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="yiJingSanTong_l10" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="yiJingSanTong_l11" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="yiJingSanTong_l12" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="yiJingSanTong_l13" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="yiJingSanTong_l14" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="yiJingSanTong_l15" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="yiJingSanTong_l16" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="yiJingSanTong_l17" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="yiJingSanTong_l18" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="yiJingSanTong_l19" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="yiJingSanTong_l20" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="yiJingSanTong_l21" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="yiJingSanTong_l22" /></td>';
		$str+='<td align="center"><a id="'+tempDelFileInfoId+'" 	href="javascript:delTr(\''+tempDelFileInfoId+'\')" >删除</a></td>';
	    $str+='</tr>';
	    $("#yiJingSanTong").before($str);

	});
	var TongXinYiJingIndex = 2;
	$("#addTongXinYiJing").click(function(){
		var tempDelFileInfoId = "TongXinYiJingIndex" + ++TongXinYiJingIndex;
	    $str='';
        $str+='<tr>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="tongXinYiJing_l1" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="tongXinYiJing_l2" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="tongXinYiJing_l3" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="tongXinYiJing_l4" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="tongXinYiJing_l5" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="tongXinYiJing_l6" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="tongXinYiJing_l7" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="tongXinYiJing_l8" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="tongXinYiJing_l9" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="tongXinYiJing_l10" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="tongXinYiJing_l11" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="tongXinYiJing_l12" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="tongXinYiJing_l13" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="tongXinYiJing_l14" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="tongXinYiJing_l15" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="tongXinYiJing_l16" /></td>';
		$str+='<td align="center"><a id="'+tempDelFileInfoId+'" 	href="javascript:delTr(\''+tempDelFileInfoId+'\')" >删除</a></td>';
	    $str+='</tr>';
	    $("#tongXinYiJing").before($str);

	});
	var PianXinYiJingIndex = 2;
	$("#addPianXinYiJing").click(function(){
		var tempDelFileInfoId = "PianXinYiJingIndex" + ++PianXinYiJingIndex;
	    $str='';
        $str+='<tr>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="pianXinYiJing_l1" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="pianXinYiJing_l2" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="pianXinYiJing_l3" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="pianXinYiJing_l4" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="pianXinYiJing_l5" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="pianXinYiJing_l6" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="pianXinYiJing_l7" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="pianXinYiJing_l8" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="pianXinYiJing_l9" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="pianXinYiJing_l10" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="pianXinYiJing_l11" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="pianXinYiJing_l12" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="pianXinYiJing_l13" /></td>';
		$str+='<td align="center"><a id="'+tempDelFileInfoId+'" 	href="javascript:delTr(\''+tempDelFileInfoId+'\')" >删除</a></td>';
	    $str+='</tr>';
	    $("#pianXinYiJing").before($str);

	});
	var ZhiGuanZuoIndex = 2;
	$("#addZhiGuanZuo").click(function(){
		var tempDelFileInfoId = "ZhiGuanZuoIndex" + ++ZhiGuanZuoIndex;
	    $str='';
        $str+='<tr>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="zhiGuanZuo_l1" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="zhiGuanZuo_l2" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="zhiGuanZuo_l3" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="zhiGuanZuo_l4" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="zhiGuanZuo_l5" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="zhiGuanZuo_l6" /></td>';
		$str+='<td align="center"><a id="'+tempDelFileInfoId+'" 	href="javascript:delTr(\''+tempDelFileInfoId+'\')" >删除</a></td>';
	    $str+='</tr>';
	    $("#zhiGuanZuo").before($str);

	});
	var JiuShiLuoWenIndex = 2;
	$("#addJiuShiLuoWen").click(function(){
		var tempDelFileInfoId = "JiuShiLuoWenIndex" + ++JiuShiLuoWenIndex;
	    $str='';
        $str+='<tr>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="jiuShiLuoWen_l1" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="jiuShiLuoWen_l2" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="jiuShiLuoWen_l3" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="jiuShiLuoWen_l4" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="jiuShiLuoWen_l5" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="jiuShiLuoWen_l6" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="jiuShiLuoWen_l7" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="jiuShiLuoWen_l8" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="jiuShiLuoWen_l9" /></td>';
		$str+='<td align="center"><a id="'+tempDelFileInfoId+'" 	href="javascript:delTr(\''+tempDelFileInfoId+'\')" >删除</a></td>';
	    $str+='</tr>';
	    $("#jiuShiLuoWen").before($str);

	});
	var ShuangSiTouIndex = 2;
	$("#addShuangSiTou").click(function(){
		var tempDelFileInfoId = "ShuangSiTouIndex" + ++ShuangSiTouIndex;
	    $str='';
        $str+='<tr>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="shuangSiTou_l1" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="shuangSiTou_l2" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="shuangSiTou_l3" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="shuangSiTou_l4" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="shuangSiTou_l5" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="shuangSiTou_l6" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="shuangSiTou_l7" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="shuangSiTou_l8" /></td>';
		$str+='<td align="center"><a id="'+tempDelFileInfoId+'" 	href="javascript:delTr(\''+tempDelFileInfoId+'\')" >删除</a></td>';
	    $str+='</tr>';
	    $("#shuangSiTou").before($str);

	});
	var DanSiTouIndex = 2;
	$("#addDanSiTou").click(function(){
		var tempDelFileInfoId = "DanSiTouIndex" + ++DanSiTouIndex;
	    $str='';
        $str+='<tr>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="danSiTou_l1" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="danSiTou_l2" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="danSiTou_l3" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="danSiTou_l4" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="danSiTou_l5" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="danSiTou_l6" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="danSiTou_l7" /></td>';
		$str+='<td align="center"><a id="'+tempDelFileInfoId+'" 	href="javascript:delTr(\''+tempDelFileInfoId+'\')" >删除</a></td>';
	    $str+='</tr>';
	    $("#danSiTou").before($str);

	});
	var LuoWenHuoIndex = 2;
	$("#addLuoWenHuo").click(function(){
		var tempDelFileInfoId = "LuoWenHuoIndex" + ++LuoWenHuoIndex;
	    $str='';
        $str+='<tr>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="luoWenHuo_l1" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="luoWenHuo_l2" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="luoWenHuo_l3" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="luoWenHuo_l4" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="luoWenHuo_l5" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="luoWenHuo_l6" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="luoWenHuo_l7" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="luoWenHuo_l8" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="luoWenHuo_l9" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="luoWenHuo_l10" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="luoWenHuo_l11" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="luoWenHuo_l12" /></td>';
		$str+='<td align="center"><a id="'+tempDelFileInfoId+'" 	href="javascript:delTr(\''+tempDelFileInfoId+'\')" >删除</a></td>';
	    $str+='</tr>';
	    $("#luoWenHuo").before($str);

	});
	var GuanMaoIndex = 2;
	$("#addGuanMao").click(function(){
		var tempDelFileInfoId = "GuanMaoIndex" + ++GuanMaoIndex;
	    $str='';
        $str+='<tr>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="guanMao_l1" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="guanMao_l2" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="guanMao_l3" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="guanMao_l4" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="guanMao_l5" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="guanMao_l6" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="guanMao_l7" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="guanMao_l8" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="guanMao_l9" /></td>';
		$str+='<td align="center"><a id="'+tempDelFileInfoId+'" 	href="javascript:delTr(\''+tempDelFileInfoId+'\')" >删除</a></td>';
	    $str+='</tr>';
	    $("#guanMao").before($str);

	});
	var DengJingLuoWenIndex = 2;
	$("#addDengJingLuoWen").click(function(){
		var tempDelFileInfoId = "DengJingLuoWenIndex" + ++DengJingLuoWenIndex;
	    $str='';
        $str+='<tr>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="dengJingLuoWen_l1" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="dengJingLuoWen_l2" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="dengJingLuoWen_l3" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="dengJingLuoWen_l4" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="dengJingLuoWen_l5" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="dengJingLuoWen_l6" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="dengJingLuoWen_l7" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="dengJingLuoWen_l8" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="dengJingLuoWen_l9" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="dengJingLuoWen_l10" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="dengJingLuoWen_l11" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="dengJingLuoWen_l12" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="dengJingLuoWen_l13" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="dengJingLuoWen_l14" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="dengJingLuoWen_l15" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="dengJingLuoWen_l16" /></td>';
		$str+='<td align="center"><a id="'+tempDelFileInfoId+'" 	href="javascript:delTr(\''+tempDelFileInfoId+'\')" >删除</a></td>';
	    $str+='</tr>';
	    $("#dengJingLuoWen").before($str);

	});
	var XiaoLuoWenIndex = 2;
	$("#addXiaoLuoWen").click(function(){
		var tempDelFileInfoId = "XiaoLuoWenIndex" + ++XiaoLuoWenIndex;
	    $str='';
        $str+='<tr>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="xiaoLuoWen_l1" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="xiaoLuoWen_l2" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="xiaoLuoWen_l3" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="xiaoLuoWen_l4" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="xiaoLuoWen_l5" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="xiaoLuoWen_l6" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="xiaoLuoWen_l7" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="xiaoLuoWen_l8" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="xiaoLuoWen_l9" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="xiaoLuoWen_l10" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="xiaoLuoWen_l11" /></td>';
		$str+='<td align="center"><a id="'+tempDelFileInfoId+'" 	href="javascript:delTr(\''+tempDelFileInfoId+'\')" >删除</a></td>';
	    $str+='</tr>';
	    $("#xiaoLuoWen").before($str);

	});
	var LuoWenGuanTiIndex = 2;
	$("#addLuoWenGuanTi").click(function(){
		var tempDelFileInfoId = "LuoWenGuanTiIndex" + ++LuoWenGuanTiIndex;
	    $str='';
        $str+='<tr>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="luoWenGuanTi_l1" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="luoWenGuanTi_l2" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="luoWenGuanTi_l3" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="luoWenGuanTi_l4" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="luoWenGuanTi_l5" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="luoWenGuanTi_l6" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="luoWenGuanTi_l7" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="luoWenGuanTi_l8" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="luoWenGuanTi_l9" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="luoWenGuanTi_l10" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="luoWenGuanTi_l11" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="luoWenGuanTi_l12" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="luoWenGuanTi_l13" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="luoWenGuanTi_l14" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="luoWenGuanTi_l15" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="luoWenGuanTi_l16" /></td>';
		$str+='<td align="center"><a id="'+tempDelFileInfoId+'" 	href="javascript:delTr(\''+tempDelFileInfoId+'\')" >删除</a></td>';
	    $str+='</tr>';
	    $("#luoWenGuanTi").before($str);

	});
	var LuoWenJieGuIndex = 2;
	$("#addLuoWenJieGu").click(function(){
		var tempDelFileInfoId = "LuoWenJieGuIndex" + ++LuoWenJieGuIndex;
	    $str='';
        $str+='<tr>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="luoWenJieGu_l1" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="luoWenJieGu_l2" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="luoWenJieGu_l3" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="luoWenJieGu_l4" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="luoWenJieGu_l5" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="luoWenJieGu_l6" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="luoWenJieGu_l7" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="luoWenJieGu_l8" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="luoWenJieGu_l9" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="luoWenJieGu_l10" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="luoWenJieGu_l11" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="luoWenJieGu_l12" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="luoWenJieGu_l13" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="luoWenJieGu_l14" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="luoWenJieGu_l15" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="luoWenJieGu_l16" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="luoWenJieGu_l17" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="luoWenJieGu_l18" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="luoWenJieGu_l19" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="luoWenJieGu_l20" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="luoWenJieGu_l21" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="luoWenJieGu_l22" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="luoWenJieGu_l23" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="luoWenJieGu_l24" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="luoWenJieGu_l25" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="luoWenJieGu_l26" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="luoWenJieGu_l27" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="luoWenJieGu_l28" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="luoWenJieGu_l29" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="luoWenJieGu_l30" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="luoWenJieGu_l31" /></td>';
		$str+='<td align="center"><a id="'+tempDelFileInfoId+'" 	href="javascript:delTr(\''+tempDelFileInfoId+'\')" >删除</a></td>';
	    $str+='</tr>';
	    $("#luoWenJieGu").before($str);

	});
    var ChouYouGanTiIndex = 2;
	$("#addChouYouGanTi").click(function(){
		var tempDelFileInfoId = "ChouYouGanTiIndex" + ++ChouYouGanTiIndex;
	    $str='';
        $str+='<tr>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="chouYouGanTi_l1" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="chouYouGanTi_l2" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="chouYouGanTi_l3" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="chouYouGanTi_l4" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="chouYouGanTi_l5" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="chouYouGanTi_l6" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="chouYouGanTi_l7" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="chouYouGanTi_l8" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="chouYouGanTi_l9" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="chouYouGanTi_l10" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="chouYouGanTi_l11" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="chouYouGanTi_l12" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="chouYouGanTi_l13" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="chouYouGanTi_l14" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="chouYouGanTi_l15" /></td>';
		$str+='<td align="center"><a id="'+tempDelFileInfoId+'" 	href="javascript:delTr(\''+tempDelFileInfoId+'\')" >删除</a></td>';
	    $str+='</tr>';
	    $("#chouYouGanTi").before($str);

	});
	var ChouYouJieGuIndex = 2;
	$("#addChouYouJieGu").click(function(){
		var tempDelFileInfoId = "ChouYouJieGuIndex" + ++ChouYouJieGuIndex;
	    $str='';
        $str+='<tr>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="chouYouJieGu_l1" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="chouYouJieGu_l2" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="chouYouJieGu_l3" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="chouYouJieGu_l4" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="chouYouJieGu_l5" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="chouYouJieGu_l6" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="chouYouJieGu_l7" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="chouYouJieGu_l8" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="chouYouJieGu_l9" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="chouYouJieGu_l10" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="chouYouJieGu_l11" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="chouYouJieGu_l12" /></td>';
		$str+='<td align="center"><a id="'+tempDelFileInfoId+'" 	href="javascript:delTr(\''+tempDelFileInfoId+'\')" >删除</a></td>';
	    $str+='</tr>';
	    $("#chouYouJieGu").before($str);

	});
	var FaMenFaLanIndex = 2;
	$("#addFaMenFaLan").click(function(){
		var tempDelFileInfoId = "FaMenFaLanIndex" + ++FaMenFaLanIndex;
	    $str='';
        $str+='<tr>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="faMenFaLan_l1" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="faMenFaLan_l2" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="faMenFaLan_l3" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="faMenFaLan_l4" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="faMenFaLan_l5" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="faMenFaLan_l6" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="faMenFaLan_l7" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="faMenFaLan_l8" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="faMenFaLan_l9" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="faMenFaLan_l10" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="faMenFaLan_l11" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="faMenFaLan_l12" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="faMenFaLan_l13" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="faMenFaLan_l14" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="faMenFaLan_l15" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="faMenFaLan_l16" /></td>';
		$str+='<td align="center"><a id="'+tempDelFileInfoId+'" 	href="javascript:delTr(\''+tempDelFileInfoId+'\')" >删除</a></td>';
	    $str+='</tr>';
	    $("#faMenFaLan").before($str);

	});
	var FaMenHanJieIndex = 2;
	$("#addFaMenHanJie").click(function(){
		var tempDelFileInfoId = "FaMenHanJieIndex" + ++FaMenHanJieIndex;
	    $str='';
        $str+='<tr>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="faMenHanJie_l1" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="faMenHanJie_l2" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="faMenHanJie_l3" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="faMenHanJie_l4" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="faMenHanJie_l5" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="faMenHanJie_l6" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="faMenHanJie_l7" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="faMenHanJie_l8" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="faMenHanJie_l9" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="faMenHanJie_l10" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="faMenHanJie_l11" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="faMenHanJie_l12" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="faMenHanJie_l13" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="faMenHanJie_l14" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="faMenHanJie_l15" /></td>';
		$str+='<td align="center"><a id="'+tempDelFileInfoId+'" 	href="javascript:delTr(\''+tempDelFileInfoId+'\')" >删除</a></td>';
	    $str+='</tr>';
	    $("#faMenHanJie").before($str);

	});
	var JueYuanJieTouIndex = 2;
	$("#addJueYuanJieTou").click(function(){
		var tempDelFileInfoId = "JueYuanJieTouIndex" + ++JueYuanJieTouIndex;
	    $str='';
        $str+='<tr>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="jueYuanJieTou_l1" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="jueYuanJieTou_l2" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="jueYuanJieTou_l3" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="jueYuanJieTou_l4" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="jueYuanJieTou_l5" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="jueYuanJieTou_l6" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="jueYuanJieTou_l7" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="jueYuanJieTou_l8" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="jueYuanJieTou_l9" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="jueYuanJieTou_l10" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="jueYuanJieTou_l11" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="jueYuanJieTou_l12" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="jueYuanJieTou_l13" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="jueYuanJieTou_l14" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="jueYuanJieTou_l15" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="jueYuanJieTou_l16" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="jueYuanJieTou_l17" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="jueYuanJieTou_l18" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="jueYuanJieTou_l19" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="jueYuanJieTou_l20" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="jueYuanJieTou_l21" /></td>';
		$str+='<td align="center"><a id="'+tempDelFileInfoId+'" 	href="javascript:delTr(\''+tempDelFileInfoId+'\')" >删除</a></td>';
	    $str+='</tr>';
	    $("#jueYuanJieTou").before($str);

	});
	var FaLanJiHeIndex = 2;
	$("#addFaLanJiHe").click(function(){
		var tempDelFileInfoId = "FaLanJiHeIndex" + ++FaLanJiHeIndex;
	    $str='';
        $str+='<tr>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="faLanJiHe_l1" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="faLanJiHe_l2" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="faLanJiHe_l3" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="faLanJiHe_l4" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="faLanJiHe_l5" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="faLanJiHe_l6" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="faLanJiHe_l7" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="faLanJiHe_l8" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="faLanJiHe_l9" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="faLanJiHe_l10" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="faLanJiHe_l11" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="faLanJiHe_l12" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="faLanJiHe_l13" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="faLanJiHe_l14" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="faLanJiHe_l15" /></td>';
		$str+='<td align="center"><a id="'+tempDelFileInfoId+'" 	href="javascript:delTr(\''+tempDelFileInfoId+'\')" >删除</a></td>';
	    $str+='</tr>';
	    $("#faLanJiHe").before($str);

	});

	var FangFuGuanIndex = 2;
	$("#addFangFuGuan").click(function(){
		var tempDelFileInfoId = "FangFuGuanIndex" + ++FangFuGuanIndex;
	    $str='';
        $str+='<tr>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="fangFuGuan_l1" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="fangFuGuan_l2" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="fangFuGuan_l3" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="fangFuGuan_l4" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="fangFuGuan_l5" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="fangFuGuan_l6" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="fangFuGuan_l7" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="fangFuGuan_l8" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="fangFuGuan_l9" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="fangFuGuan_l10" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="fangFuGuan_l11" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="fangFuGuan_l12" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="fangFuGuan_l13" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="fangFuGuan_l14" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="fangFuGuan_l15" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="fangFuGuan_l16" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="fangFuGuan_l17" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="fangFuGuan_l18" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="fangFuGuan_l19" /></td>';
		$str+='<td align="center"><a id="'+tempDelFileInfoId+'" 	href="javascript:delTr(\''+tempDelFileInfoId+'\')" >删除</a></td>';
	    $str+='</tr>';
	    $("#fangFuGuan").before($str);

	});
	var YouTaoGuanGuanTiIndex = 2;
	$("#addYouTaoGuanGuanTi").click(function(){
		var tempDelFileInfoId = "YouTaoGuanGuanTiIndex" + ++YouTaoGuanGuanTiIndex;
	    $str='';
        $str+='<tr>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="youTaoGuanGuanTi_l1" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="youTaoGuanGuanTi_l2" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="youTaoGuanGuanTi_l3" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="youTaoGuanGuanTi_l4" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="youTaoGuanGuanTi_l5" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="youTaoGuanGuanTi_l6" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="youTaoGuanGuanTi_l7" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="youTaoGuanGuanTi_l8" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="youTaoGuanGuanTi_l9" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="youTaoGuanGuanTi_l10" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="youTaoGuanGuanTi_l11" /></td>';
		$str+='<td align="center"><a id="'+tempDelFileInfoId+'" 	href="javascript:delTr(\''+tempDelFileInfoId+'\')" >删除</a></td>';
	    $str+='</tr>';
	    $("#youTaoGuanGuanTi").before($str);

	});
	var YouTaoGuanJieGuIndex = 2;
	$("#addYouTaoGuanJieGu").click(function(){
		var tempDelFileInfoId = "YouTaoGuanJieGuIndex" + ++YouTaoGuanJieGuIndex;
	    $str='';
        $str+='<tr>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="youTaoGuanJieGu_l1" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="youTaoGuanJieGu_l2" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="youTaoGuanJieGu_l3" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="youTaoGuanJieGu_l4" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="youTaoGuanJieGu_l5" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="youTaoGuanJieGu_l6" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="youTaoGuanJieGu_l7" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="youTaoGuanJieGu_l8" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="youTaoGuanJieGu_l9" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="youTaoGuanJieGu_l10" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="youTaoGuanJieGu_l11" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="youTaoGuanJieGu_l12" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="youTaoGuanJieGu_l13" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="youTaoGuanJieGu_l14" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="youTaoGuanJieGu_l15" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="youTaoGuanJieGu_l16" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="youTaoGuanJieGu_l17" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="youTaoGuanJieGu_l18" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="youTaoGuanJieGu_l19" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="youTaoGuanJieGu_l20" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="youTaoGuanJieGu_l21" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="youTaoGuanJieGu_l22" /></td>';
		$str+='<td align="center"><a id="'+tempDelFileInfoId+'" 	href="javascript:delTr(\''+tempDelFileInfoId+'\')" >删除</a></td>';
	    $str+='</tr>';
	    $("#youTaoGuanJieGu").before($str);

	});
	var ZuanJuLuoWen1Index = 2;
	$("#addZuanJuLuoWen1").click(function(){
		var tempDelFileInfoId = "ZuanJuLuoWen1Index" + ++ZuanJuLuoWen1Index;
	    $str='';
        $str+='<tr>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="zuanJuLuoWen_l1" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="zuanJuLuoWen_l2" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="zuanJuLuoWen_l3" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="zuanJuLuoWen_l4" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="zuanJuLuoWen_l5" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="zuanJuLuoWen_l6" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="zuanJuLuoWen_l7" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="zuanJuLuoWen_l8" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="zuanJuLuoWen_l9" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="zuanJuLuoWen_l10" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="zuanJuLuoWen_l11" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="zuanJuLuoWen_l12" /></td>';
		$str+='<td align="center"><a id="'+tempDelFileInfoId+'" 	href="javascript:delTr(\''+tempDelFileInfoId+'\')" >删除</a></td>';
	    $str+='</tr>';
	    $("#zuanJuLuoWen1").before($str);
    });
    var ZuanJuLuoWen2Index = 2;
	$("#addZuanJuLuoWen2").click(function(){
		var tempDelFileInfoId = "ZuanJuLuoWen2Index" + ++ZuanJuLuoWen2Index;
	    $str='';
        $str+='<tr>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="zuanJuLuoWen_ll1" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="zuanJuLuoWen_ll2" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="zuanJuLuoWen_ll3" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="zuanJuLuoWen_ll4" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="zuanJuLuoWen_ll5" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="zuanJuLuoWen_ll6" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="zuanJuLuoWen_ll7" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="zuanJuLuoWen_ll8" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="zuanJuLuoWen_ll9" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="zuanJuLuoWen_ll10" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="zuanJuLuoWen_ll11" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="zuanJuLuoWen_ll12" /></td>';
		$str+='<td align="center"><a id="'+tempDelFileInfoId+'" 	href="javascript:delTr(\''+tempDelFileInfoId+'\')" >删除</a></td>';
	    $str+='</tr>';
	    $("#zuanJuLuoWen2").before($str);
    });
    var GangBanWaiGuanIndex = 2;
	$("#addGangBanWaiGuan").click(function(){
		var tempDelFileInfoId = "GangBanWaiGuanIndex" + ++GangBanWaiGuanIndex;
	    $str='';
        $str+='<tr>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="gangBanWaiGuan_l1" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="gangBanWaiGuan_l2" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="gangBanWaiGuan_l3" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="gangBanWaiGuan_l4" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="gangBanWaiGuan_l5" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="gangBanWaiGuan_l6" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="gangBanWaiGuan_l7" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="gangBanWaiGuan_l8" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="gangBanWaiGuan_l9" /></td>';
		$str+='<td align="center"><a id="'+tempDelFileInfoId+'" 	href="javascript:delTr(\''+tempDelFileInfoId+'\')" >删除</a></td>';
	    $str+='</tr>';
	    $("#gangBanWaiGuan").before($str);

	});
	var FengTouJiHeIndex = 2;
	$("#addFengTouJiHe").click(function(){
		var tempDelFileInfoId = "FengTouJiHeIndex" + ++FengTouJiHeIndex;
	    $str='';
        $str+='<tr>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="fengTouJiHe_l1" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="fengTouJiHe_l2" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="fengTouJiHe_l3" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="fengTouJiHe_l4" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="fengTouJiHe_l5" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="fengTouJiHe_l6" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="fengTouJiHe_l7" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="fengTouJiHe_l8" /></td>';
		$str+='<td align="center"><a id="'+tempDelFileInfoId+'" 	href="javascript:delTr(\''+tempDelFileInfoId+'\')" >删除</a></td>';
	    $str+='</tr>';
	    $("#fengTouJiHe").before($str);

	});
	var YaLiRongQiIndex = 2;
	$("#addYaLiRongQi").click(function(){
		var tempDelFileInfoId = "YaLiRongQiIndex" + ++YaLiRongQiIndex;
	    $str='';
        $str+='<tr>';
		$str+='<td align="center" colspan="2"><input class="input_60 easyui-validatebox" type="text" name="yaLiRongQi_l1" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="yaLiRongQi_l2" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="yaLiRongQi_l3" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="yaLiRongQi_l4" /></td>';
		$str+='<td align="center"><a id="'+tempDelFileInfoId+'" 	href="javascript:delTr(\''+tempDelFileInfoId+'\')" >删除</a></td>';
	    $str+='</tr>';
	    $("#yaLiRongQi").before($str);

	});
	var LengWanGuanIndex = 2;
	$("#addLengWanGuan").click(function(){
		var tempDelFileInfoId = "LengWanGuanIndex" + ++LengWanGuanIndex;
	    $str='';
        $str+='<tr>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="lengWanGuan_l1" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="lengWanGuan_l2" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="lengWanGuan_l3" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="lengWanGuan_l4" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="lengWanGuan_l5" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="lengWanGuan_l6" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="lengWanGuan_l7" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="lengWanGuan_l8" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="lengWanGuan_l9" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="lengWanGuan_l10" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="lengWanGuan_l11" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="lengWanGuan_l12" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="lengWanGuan_l13" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="lengWanGuan_l14" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="lengWanGuan_l15" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="lengWanGuan_l16" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="lengWanGuan_l17" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="lengWanGuan_l18" /></td>';
		$str+='<td align="center"><a id="'+tempDelFileInfoId+'" 	href="javascript:delTr(\''+tempDelFileInfoId+'\')" >删除</a></td>';
	    $str+='</tr>';
	    $("#lengWanGuan").before($str);

	});
	var BaZiMangBanIndex = 2;
	$("#addBaZiMangBan").click(function(){
		var tempDelFileInfoId = "BaZiMangBanIndex" + ++BaZiMangBanIndex;
	    $str='';
        $str+='<tr>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="baZiMangBan_l1" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="baZiMangBan_l2" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="baZiMangBan_l3" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="baZiMangBan_l4" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="baZiMangBan_l5" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="baZiMangBan_l6" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="baZiMangBan_l7" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="baZiMangBan_l8" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="baZiMangBan_l9" /></td>';
		$str+='<td align="center"><a id="'+tempDelFileInfoId+'" 	href="javascript:delTr(\''+tempDelFileInfoId+'\')" >删除</a></td>';
	    $str+='</tr>';
	    $("#baZiMangBan").before($str);

	});
	var FaLanGaiIndex = 2;
	$("#addFaLanGai").click(function(){
		var tempDelFileInfoId = "FaLanGaiIndex" + ++FaLanGaiIndex;
	    $str='';
        $str+='<tr>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="faLanGai_l1" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="faLanGai_l2" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="faLanGai_l3" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="faLanGai_l4" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="faLanGai_l5" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="faLanGai_l6" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="faLanGai_l7" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="faLanGai_l8" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="faLanGai_l9" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="faLanGai_l10" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="faLanGai_l11" /></td>';
		$str+='<td align="center"><a id="'+tempDelFileInfoId+'" 	href="javascript:delTr(\''+tempDelFileInfoId+'\')" >删除</a></td>';
	    $str+='</tr>';
	    $("#faLanGai").before($str);

	});
	var ShenHeJiLuIndex = 2;
	$("#addShenHeJiLu").click(function(){
		var tempDelFileInfoId = "ShenHeJiLuIndex" + ++ShenHeJiLuIndex;
	    $str='';
        $str+='<tr>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="shenHeJiLu_l1" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="shenHeJiLu_l2" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="shenHeJiLu_l3" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="shenHeJiLu_l4" /></td>';
		$str+='<td align="center"><input class="input_60 easyui-validatebox" type="text" name="shenHeJiLu_l5" /></td>';
		$str+='<td align="center"><a id="'+tempDelFileInfoId+'" 	href="javascript:delTr(\''+tempDelFileInfoId+'\')" >删除</a></td>';
	    $str+='</tr>';
	    $("#shenHeJiLu").before($str);

	});






});

function delTr(tempTdId){//删除
	var obj  = $("#" + tempTdId);
	$(obj).parent().parent().remove();  
}
